<a href="https://colab.research.google.com/github/bhagu/Python-for-Machine-Learning-and-Data-Science/blob/main/Python/NumPy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
mylist

[1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
myarr = np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
type(my_matrix)

list

In [11]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5,))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])